apiVersion: v1
kind: Service
metadata:
  name: image-gallery
spec:
  ports:
    - port: 80
      targetPort: web
  selector:
    app: apod-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apod-web
spec:
  selector:
    matchLabels:
      app: apod-web
  template:
    metadata:
      labels:
        app: apod-web
    spec:
      containers:
        - name: web
          image: sixeyed/image-gallery
          ports:
            - containerPort: 80
              name: web